### ISSUE TITLE
Establish 2 way communication with graph oracle

### ISSUE THREAD

**Issue by ptierney** [ptierney/AutoDJ#2]
Establish 2 way communication with Graph Oracle server, Sylvester. Decide if Http or sockets.

**Comment by njoubert** [comment]
HTTP is a very lightweight protocol, so we can write our own socket-based http client with which you can send me data, it won't be very much code - i can probably put this together in an evening, but there's definitely things out there already. Since we only need a subset of true HTTP communication, writing our own is simple, but why reinvent the wheel.
